framework:
    secret:          "98ay9afy9ahrahv9a8s87idgasiueiarufoag8o8aosdyaoshea8"
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    router:          {resource: ~}
    templating:      {engines: ['twig']}
    default_locale:  "en"

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

services:
    discord_error_handler:
        class: Discord\Base\AppBundle\Logger\Handler\ErrorHandler
        arguments:
            - "%error_channel_id%"
            - "%pastebin%"
        calls:
            - ["setDiscord", ["@discord"]]
    bot_formatter:
        class: Symfony\Bridge\Monolog\Formatter\ConsoleFormatter
        arguments:
            - "[%%datetime%%] %%start_tag%%%%message%%%%end_tag%% (%%level_name%%) %%context%% %%extra%%\n"
            - 'Y-m-d H:i:s'
            - true

monolog:
    handlers:
        main:
            type:   stream
            path:   "%log_dir%/%name%.log"
            level:  debug
        error:
            type: service
            id:   discord_error_handler
    channels: ['bot']
