framework:
    secret:          "98ay9afy9ahrahv9a8s87idgasiueiarufoag8o8aosdyaoshea8"
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    router:          {resource: ~}
    templating:      {engines: ['php']}
    default_locale:  "en"

monolog:
    handlers:
        main:
            type:   stream
            path:   "%log_dir%/%name%.log"
            level:  debug
