Discord\Base\AppBundle\Model\Module:
    type: entity
    table: module
    indexes:
        name_index:
            columns: [ name ]
        default_enabled_index:
            columns: [ defaultEnabled ]
        disableable_index:
            columns: [ disableable ]
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            unique: true
            type: string
            length: 64
        defaultEnabled:
            type: boolean
        disableable:
            type: boolean
