Discord\Base\AppBundle\Model\Server:
    type: mappedSuperclass
    table: server
    indexes:
        identifier_index:
            columns: [ identifier ]
        owner_index:
            columns: [ owner ]
        prefix_index:
            columns: [ prefix ]
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        identifier:
            unique: true
            type: string
            length: 64
        owner:
            type: string
            length: 64
        prefix:
            type: string
            length: 8
    oneToMany:
        modules:
            targetEntity: Discord\Base\AppBundle\Model\ServerModule
            mappedBy: server
