Discord\Base\AppBundle\Model\ServerModule:
    type: entity
    table: server_module
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        enabled:
            type: boolean
    manyToOne:
        module:
            targetEntity: Discord\Base\AppBundle\Model\Module
    uniqueConstraints:
        identity_index:
            columns: [ server_id, module_id ]
