Discord\Base\AppBundle\Model\Server:
    type: mappedSuperclass
    collection: servers
    indexes:
        identifier_index:
            keys:
                identifier: asc
            options:
                unique: true
                dropDups: true
                safe: true
        owner_index:
            keys:
                owner: asc
        prefix_index:
            keys:
                prefix: asc
    fields:
        id:
            id: true
        identifier:
            type: string
        owner:
            type: string
        prefix:
            type: string
    embedMany:
        modules:
            targetDocument: Discord\Base\AppBundle\Model\ServerModule
